#!/bin/sh
set -e

case "$1" in
    configure)
        # Update the icon cache for the system directory
        if [ -x /usr/bin/gtk-update-icon-cache ]; then
            gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
        fi

        # Update the desktop database to register the .desktop file
        if [ -x /usr/bin/update-desktop-database ]; then
            update-desktop-database -q /usr/share/applications || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
